### ISSUE TITLE
remove tibble dependency 

### ISSUE THREAD

**Issue by kieranjmartin** [gowerc/diffdf#18]
No longer used for print functionality, we can switch to nested lists with some recoding

**Comment by gowerc** [comment]
We also use tibble for storing list columns for the attributes (and maybe classes as well). 

See:
https://github.com/gowerc/diffdf/blob/6510b7d26158bc6c804c0f5b83443421ba093cbb/R/identify.R#L165


But agreed it would be good to perge tibble as well from our dependency list (though we might need to keep it in the tests to ensure we can still compare tibbles given how common of a data source they are now)

**Comment by kieranjmartin** [comment]
While I think we can just have a list of lists, I actually was thinking this through and actually the functionality we get from returning tibbles is quite high, as it makes the objects just nicer to look at, so I'm inclined to actually leave the dependency for now

**Comment by gowerc** [comment]
Going to close this as at the moment I am no rush to remove tibbles as the print method is very nice !
