### ISSUE TITLE
Issue with RNG 

### ISSUE THREAD

**Issue by gowerc** [gowerc/diffdf#21]
@kieranjmartin , FYI I got the following via email:

Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_diffdf.html>.

The check problems with current R-devel are from

     • The default method for generating from a discrete uniform
       distribution (used in sample(), for instance) has been changed.
       ...
       The previous method can be requested using RNGkind() or
       RNGversion() if necessary for reproduction of old results.

To make your package successfully pass the checks for current R-devel
and R-release you may find it most convenient to insert

  suppressWarnings(RNGversion("3.5.0"))

before calling set.seed() in your example, vignette and test code (where
the difference in RNG sample kinds matters, of course).

Note that this ensures using the (old) non-uniform "Rounding" sampler
for all 3.x versions of R, and does not add an R version dependency.
Note also that the new "Rejection" sampler which R will use from 3.6.0
onwards by default is definitely preferable over the old one, so that
the above should really only be used as a temporary measure for
reproduction of the previous behavior (and the run time tests relying on
it).

Please correct before 2019-03-20 to safely retain your package on CRAN.

Best,
-k

**Comment by kieranjmartin** [comment]
While the PR fixes this, I recommend that we leave this issue open so we can update to use the new sampler with 3.6.

It's not clear to me how this works in the cran world, as this would mean our tests would perform different when tested on different versions of R? This is driven by our print tests, where the data is a little different under different samplers. One slightly hacky solution would be to fix the test data by saving it internally or just explicitly defining it.

**Comment by gowerc** [comment]
@kieranjmartin 

So yer, as you stated, the issue for us is that we generate some test data using `sample()`. Parts of this data are then printed in our tests the results of which we compare to against with subsequent runs of the test to ensure nothing has changed. 

In general I think I am happy with the solution of just fixing the sampler version.  Though I guess it is safer and more sensible to hand create the data as a CSV file n the utilities folder then as part of the build process read this in and save it as an internal R object.

**Comment by gowerc** [comment]
Fixed in V2
