### ISSUE TITLE
Idea: add an argument to select which tests should be passed

### ISSUE THREAD

**Issue by ericlecoutre** [gowerc/diffdf#26]
Hi,

I discovered the package today: nice work.
In this context, that would be nice to have the possibility to deselect the test on rows: only to check if dataframe has similar structure (columns) and/or compare factors levels.
This could very useful for gloabal data quality for instance to compare two outputs generated at different times we know there will be different rows (think about training a predictive model and applying on a new population: only change in strcuture/levels would be of interest)

Eric

**Comment by kieranjmartin** [comment]
Thanks @ericlecoutre , I think this is potentially a good idea, I think @gowerc to implement this and other ideas we definitely would need to move options into a list, as suggested in #13

**Comment by gowerc** [comment]
Hi @ericlecoutre, 

I like this idea as well :) 

It also has the secondary benefit/use case that for large datasets you can ensure that the overall structure is correct before delving into the expensive process of checking values. 

Will add to the development list - thank you !

**Comment by gowerc** [comment]
Closed in favour of #45
