### ISSUE TITLE
Function Naiming

### ISSUE THREAD

**Issue by gowerc** [gowerc/diffdf#29]
@kieranjmartin ,

I don't really have a solution but I'm still not happy with the naming of our external facing functions.  Currently there is:
```
diffdf_issuerows
diffdf_has_issue
```

I think the `diffdf_` prefix is a bit clunky and long.  The original idea was to make functions easy to search for on the auto complete mirroring what was done with `str_` in stringr and `fct_` in forcats.  However I realise now all those prefixed functions all relate to specific operations (i.e. all functions related to manipulating strings however there are functions in each of those packages that don't have the prefix as they have other purposes i.e. `regex`, `boundary` & `fixed`

I'm wondering if we should just drop the diffdf prefix (or reduce to just `df_`?)  or find another name ?

**Comment by kieranjmartin** [comment]
it's a shame R6 isn't more accepted, because the obvious thing to do is just make these methods of an rcompare object. 

I don't think there's a great solution. Moving to has_issue and get_issue_rows is fine, but loses the connection to diffdf. Maybe it's ok
