### ISSUE TITLE
Handling cases when there are duplicate values in the key variable

### ISSUE THREAD

**Issue by wyf88** [gowerc/diffdf#33]
For example when I try to compare the AE domain data at two different time points, it seems that `AE.AESPID` is the only appropriate identifier for each AE record to be used as the key variable for diffdf. However, there are always different AE records with the same AESPID, so when I try `diffdf(AE0, AE, "AESPID")` it will fail with the following error message:
```
Error in diffdf::diffdf(AE0_cut, AE_cut, "AESPID") : 
  BY variables in BASE do not result in unique observations
```

My question is, do you think the function can be extended to allow for duplicate values in the key variables, or do you have any other better solutions? Many thanks!

Yifan Wang

**Comment by kieranjmartin** [comment]
Hi @wyf88 , I think in this use case you can use c("USUBJID", "AESPID") to uniquely identify a patient.

 In general if you can't uniquely identify by variables you can use row number, I don't know how one could meaningfully compare two data frames when you can't uniquely compare rows.

Hope this is helpful.

**Comment by wyf88** [comment]
Hi @kieranjmartin , thanks a lot for your suggestion! Unfortunately it seems that records with the same AESPID are often (if not always) from the same patient, so AESPID+USUBJID does not define a unique row either. I also considered adding other variables (e.g. AETERM, AEDECOD), but there is possibility that the reported/coded term is updated in the new data frame, and thus the record cannot be matched from the two data frames.

For now the workaround I'm using is either to include AEDECOD to the key variables (with the caveat mentioned), or to remove the records with duplicate AESPID first before comparing, considering that they only add up to a small proportion. I'm just wondering if there is a better solution. 

Thank you!

**Comment by kieranjmartin** [comment]
Hi @wyf88 this surprises me: I thought that the standard was to have a unique AESPID for each test so I would expect that to work. Perhaps as you say AEDECOD is needed as well for a true unique identity!

I think that in principle that for the goal of comparing two datasets which are identical, I don't know exactly how I would compare two datasets where I cannot uniquely identify rows without basically brute searching.

I can imagine something like if I have a case where on an id if dataset A has rows 1,2 and dataset B has rows 3,4 we could compare 1 with 3 and 4, and 2 with 3 and 4, and provide information on each of these combinations, but I think that would be very messy, and break a lot of core assumptions in diffdf functionality.

**Comment by gowerc** [comment]
Hi @wyf88 ,

I think @kieranjmartin  has covered this pretty well.  

To answer your question directly though I don't think we have any plans to extend the package for duplicate key values.  For one our entire code base is designed around this assumption and it would mean a major overhaul.  Secondly, as mentioned by Kieran,  I'm not sure comparisons without this assumption are meaningful.   If you can't define what makes a unique observation how can you meaningfully check to see if it exists or has changed in another dataset ? 

Things I would want to check include:   are these records with the same AESPID  not just pure duplicates ?  If not are they potentially the same AE with an upgraded severity (thus can you use severity in the key)?   Can you differentiate between the records based on their date time?    Finally maybe go back to data management as I was under the impression AESPID should be unique.

My feeling is that this is a limitation more with the dataset than the functionality of the package and as such I think I will close this ticket.  Please feel free to re-open though if you would like to discuss potential enhancements or how they might look further !
