### ISSUE TITLE
Option to exclude columns

### ISSUE THREAD

**Issue by gowerc** [gowerc/diffdf#38]
A feature I saw in another comparison package which I think might be useful for us to implement is the option for the user to omit columns as part of their comparison  or/and the ability to only compare specific columns.

Perhaps

```
diffdf( iris, iris ,  column_exclude = c("Sepal.Length") )
diffdf( iris, iris ,  column_include = c("Species", "Sepal.Width"))
```

Having just said that I guess if the user wanted to do this they could just simply filter their dataset prior to the comparison ? 

What do you think @kieranjmartin

**Comment by kieranjmartin** [comment]
This seems pretty edge casey to me. I imagine it's not very hard to implement but I don't see much value to it

**Comment by gowerc** [comment]
yer on reflection this is not needed, users can very simply do :

```
dat_update <- dat %>% select( - Sepal.Length)
```

This adds almost no value and increases code / testing complexity unnecessarily
