### ISSUE TITLE
add format and show methods

### ISSUE THREAD

**Issue by kieranjmartin** [gowerc/diffdf#43]
Currently we just use print() but we should ideally define a format method and show

**Comment by gowerc** [comment]
Hey @kieranjmartin , 

Apologies for being slow here but I'm not sure I quite follow, would you mind adding some more details to what you mean here ?

**Comment by kieranjmartin** [comment]
sorry, I mean we should move the part of print which creates an object to format, and print just uses cat, from Advanced R:

"If you’re implementing more complicated print() methods, it’s a better idea to implement format() methods that return a string, and then implement print.class <- function(x, ...) cat(format(x, ...), "\n". This makes for methods that are much easier to compose, because the side-effects are isolated to a single place."

**Comment by gowerc** [comment]
Interesting,  I mean I'm sure the authors of advanced R are correct but I'm not quite sure initially why this makes any meaningful difference ?  Are they basically advocating a separation of the logic of rendering a string from that of printing ? 

Also then why format and not `as.character()` ?

**Comment by kieranjmartin** [comment]
I don't think its a huge difference, it just makes testing a little easier I think, because the printed object might be different due to system differences. 

I don't think this is a big deal, I think it's just convention: maybe need to do a survey of a few packages to see how common it is

**Comment by gowerc** [comment]
Decided not to do
