### ISSUE TITLE
class based design of diffdf 

### ISSUE THREAD

**Issue by kieranjmartin** [gowerc/diffdf#59]
So in this https://github.com/gowerc/diffdf/pull/58 I started thinking about how we structure our diffdf object. I know we originally stripped out the class based stuff as it was complexity for no purpose but I' wondering.

If we can define an ordered list of tests, which depend on the previous tests (which optionally return columns which should be excluded from the next test) then we can clean up diffdf.R substantially. With the correct design, this also allows us to make an extensible framework which will help us if we want to add more tests in future, and also potentially could allow other users of the package to add tests of their own.

I think in this new paradigm I think I would want to return an S3 amenable object for most use, but make the underlying R6 (or whatever framework we use) object accessible via some accessor function

**Comment by gowerc** [comment]
Yer I've been trying out different ideas in my head but am struggling to nail down the best way of doing this,  I think combining it with the HTML update would be a good idea as that PR already requires substantial code edits that I feel it would be good to get them all over and done with at once. 

Currently, I'm thinking of having something like:

```
base_object
    source_base_data
    source_compare_data
    current_base_data (stripped of excluded columns / rows)
    current_compare_data (stripped of excluded columns / rows)
    keys
    options
    list of issues (ordered) with pass/fail/ND state + index locations (more below)
    list of display objects


display object
    title  
    body - list each element can be either string or dataframe
    footer
    order number
```

Essentially I am trying to decouple the "issues" from the display objects as at the moment I am having to create fake issues to inject things like headers and footers to the report.

The list of issues will be the main things to be checked which will have the result set to pass-fail or ND  (my theory is that all tests should always be run but the state just set to ND if the user didn't want it).   Also in this list we can put indexes of where the issues occur for traceback.

source_data is just the original untouched dataset whilst current_data is the filtered/converted data that always contains the variables to be operated on (i.e. there is no "exclude list" the variables are just taken out of the current_data set.

The finally a dedicated display object which will have its own methods to render each object into a HTML / markdown fragment which are then combined together to make the actual print out

**Comment by gowerc** [comment]
@kieranjmartin 

Yer I've been trying out different ideas in my head but am struggling to nail down the best way of doing this,  I think combining it with the HTML update would be a good idea as that PR already requires substantial code edits that I feel it would be good to get them all over and done with at once. 

Currently, I'm thinking of having something like:

```
base_object
    source_base_data
    source_compare_data
    current_base_data (stripped of excluded columns / rows)
    current_compare_data (stripped of excluded columns / rows)
    keys
    options
    list of issues (ordered) with pass/fail/ND state + index locations (more below)
    list of display objects


display object
    title  
    body - list each element can be either string or dataframe
    footer
    order number
```

Essentially I am trying to decouple the "issues" from the display objects as at the moment I am having to create fake issues to inject things like headers and footers to the report.

The list of issues will be the main things to be checked which will have the result set to pass-fail or ND  (my theory is that all tests should always be run but the state just set to ND if the user didn't want it).   Also in this list we can put indexes of where the issues occur for traceback.

source_data is just the original untouched dataset whilst current_data is the filtered/converted data that always contains the variables to be operated on (i.e. there is no "exclude list" the variables are just taken out of the current_data set.

The finally a dedicated display object which will have its own methods to render each object into a HTML / markdown fragment which are then combined together to make the actual print out

**Comment by kieranjmartin** [comment]
I think I need to understand the need for fake issues a bit more. My feeling is that we should have two classes

1) diffdf object, which is pretty much as you defined
2) issue, which contains the methods for running the comparison, and the methods for displaying that issue.

Can you help me understand why we need a seperate display object? I feel like they would always be associated with issues?

**Comment by gowerc** [comment]
@kieranjmartin ,

Ok what about the following:

```
diffMain
    base - Df
    comp - Df
    keys - character string
    opts - list
    diffResult - a diffResult
    perform_check(checkfun)
    
diffResult
    opts - list
    checks - list of checkResults
    result - T/F
    dfsummary - displayObj

checkResult
    name - character string
    display -  A display object
    result -  "passed" / "failed" / "not-done"
    message - Character string to print in warning
    data - Summary data used for traceback
    exclude_cols - character vector
    exclude_rows - numeric vector
    
displayObj
    title - character vector
    body - a list containing only character vectors or data.frames
    footnote - character vector
    render_html()
    render_ascii()
    render_markdown()
```

So:
 
- diffMain is the main driver object used within the functions to coordinate everything
- diffResult is the final object we return to users. We also then have a summary() function that converts it into a more user friendly list (similar to how what diffdf returns now)
- checkResult is returned by any check we do, each check must be formatted as a function(base, comp, keys, opts) which returns a checkResult object
- displayObjs are just the generic form of what we want to show users which will have a render method attached for the different output types 


I really think this structure makes sense. I have made a start at it in the following branch to try and show how it could work: https://github.com/gowerc/diffdf/tree/v2

Let me know what you think
