### ISSUE TITLE
Allow for order-agnostic comparison between data frames

### ISSUE THREAD

**Issue by kieran-mace** [gowerc/diffdf#64]
It would be nice to be able to consider two data frames that are not ordered the same way:

For example, it would be nice to have an option wherethese two `data.frame`s are equivalent. 

```
library(tidyverse)
library(diffdf)

df_a = data.frame(letter_col = letters[1:4], number_col = 1:4)

df_b = df_a %>% arrange(desc(number_col))

diffdf::diffdf(df_a, df_b)
```

**Comment by gowerc** [comment]
Closing as we think the current implementation of diffdf can handle this. Please let us know if we have misunderstood your issue
