### ISSUE TITLE
Differerntly named keys for each dataset?

### ISSUE THREAD

**Issue by astraetech** [gowerc/diffdf#65]
HI,

I was wondering if the differently names keys like in dplyr joins could be implemented. HEre is an example:

```
diffdf(top1000_hist , tn_msa_100_hpi_cur , keys = c("fhfa_msa_code" =
                                                                      "tn_msa_fhfa_msa_code_1", "fyear" = "tn_msa_year_1") )
```
I come from SAS and SQL so the keys are usually named never the same. Could it be possible to implement this? Thank you!

**Comment by kieranjmartin** [comment]
@astraetech apologies for the delayed response to this.

The prime reason for diffdf is to act like proc compare, so in general we expect the keys variables to have the same name. It is something that wouldn't be too hard to implement; I can imagine there are use cases where this could be useful

**Comment by gowerc** [comment]
Decided that we are not going to implement this, we recommend making an explicit rename prior to using diffdf, feel free to discuss further if this is inappropriate
