### ISSUE TITLE
data table comparison overflow

### ISSUE THREAD

**Issue by kieranjmartin** [gowerc/diffdf#66]
See https://github.roche.com/enabler/MN39159/issues/225 (internal roche issue)

The key part:

The issue is due to all_data$visits being a data.table rather than a tibble/data frame.
Using diffdf on adsl with itself takes 0.4 sec (or less), diffdf on a adsl converted to a data.table takes 22 secs (or more). So it takes around 50 times as long if one of the comparisons is a data.table.

So it seems something about data tables causes us big issues; not sure which part is causing this exactly!

**Comment by gowerc** [comment]
Does this issue exist on the master or devel branch (or both) ?

**Comment by kieranjmartin** [comment]
I think master; I haven't replicated this bug myself yet so couldn't say for sure

**Comment by gowerc** [comment]
Solved by most recent re-implementation of diffdf internals #67
