### ISSUE TITLE
Issue when base and compare dataframe no longer have any matching key records

### ISSUE THREAD

**Issue by sclewis23** [gowerc/diffdf#77]
We are using diffdf to track changes to dataframes every day, and we ran into an issue where the base dataframe no longer has any records (based on the key column) in the compare dataframe.  I would think that diffdf would indicate that all base rows were deleted and all the compare rows were added.
getting error:
Error in `[[<-.data.frame`(`*tmp*`, "VARIABLE", value = "num"): replacement has 1 row, data has 0

version diffdf 1.0.4
`
``` r
old_df <- tibble::tibble(num = 1:2,
                         id = 1:2)

new_df <- tibble::tibble(num = 1:3,
                         id = 1:3)
diffdf::diffdf(base = old_df, compare = new_df, keys = "id")
#> Warning in diffdf::diffdf(base = old_df, compare = new_df, keys = "id"): 
#> There are rows in COMPARE that are not in BASE !!
#> Differences found between the objects!
#> 
#> A summary is given below.
#> 
#> There are rows in COMPARE that are not in BASE !!
#> All rows are shown in table below
#> 
#>   ====
#>    id 
#>   ----
#>    3  
#>   ----

old_df <- tibble::tibble(num = 1:2,
                         id = 4:5)
diffdf::diffdf(base = old_df, compare = new_df, keys = "id")
#> Error in `[[<-.data.frame`(`*tmp*`, "VARIABLE", value = "num"): replacement has 1 row, data has 0

sessionInfo()
#> R version 4.0.0 (2020-04-24)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Red Hat Enterprise Linux
#> 
#> Matrix products: default
#> BLAS:   /opt/R/R_4.0.0/lib64/R/lib/libRblas.so
#> LAPACK: /opt/R/R_4.0.0/lib64/R/lib/libRlapack.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.13   knitr_1.33        magrittr_2.0.1    diffdf_1.0.4     
#>  [5] rlang_0.4.11      fansi_0.5.0       stringr_1.4.0     highr_0.9        
#>  [9] tools_4.0.0       xfun_0.24         utf8_1.2.1        cli_3.0.0        
#> [13] withr_2.4.2       htmltools_0.5.1.1 ellipsis_0.3.2    yaml_2.2.1       
#> [17] digest_0.6.27     tibble_3.1.2      lifecycle_1.0.0   crayon_1.4.1     
#> [21] vctrs_0.3.8       fs_1.5.0          glue_1.4.2        evaluate_0.14    
#> [25] rmarkdown_2.9     reprex_2.0.0      stringi_1.6.2     compiler_4.0.0   
#> [29] pillar_1.6.1      pkgconfig_2.0.3
```

<sup>Created on 2021-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

`

**Comment by gowerc** [comment]
Thanks for highlighting this. Will take a look and try and make a patch

**Comment by StefanThoma** [comment]
I ran into a similar problem where one of my key variables was all upper-case in COMP but lower-case in BASE. 
It was tricky to debug. 
Maybe an intersection check of key variables would be useful, something like this: 


`valid_key_vars <- function(BASE, COMP, KEYS){
  does_it_intersect <- function(one_key){
    intersection <- intersect(BASE[[one_key]], COMP[[one_key]])
    
    min(length(intersection), 1) |> as.logical()
  }
  check <- sapply(KEYS, FUN = does_it_intersect)

  if(!any(check)){
    return()
  }
  
  res1 <- paste("it looks like some of the key variables differ between the data-sets, namely: ", paste(names(check[!check]), collapse = " "))
  

  res2 <- kableExtra::kable(cbind(head(BASE[names(check[!check])], 3), head(COMP[names(check[!check])], 3)))
  return(list(res1, res2))
}
`

**Comment by kieranjmartin** [comment]
Going to close this as capture in #79
