### ISSUE TITLE
get names from function input?

### ISSUE THREAD

**Issue by kieranjmartin** [gowerc/diffdf#9]
Could replace BASE/COMPARE with dataset names... this would be hard to ensure standard print sizes though

**Comment by gowerc** [comment]
I can't make up my mind on this. 
One side it would make the   print messages a lot more meaningful  but yer having users enter abritrary lengthed names is likely to be a pain.

also in terms of processing the finished datasets it means the tibble variable names are not set. 

I would be up for doing some sort of labeling in the print method only i.e.

```
|  variable  |   base (dsin1)  |   compare (dsin2)  |
-------------------------------------------------
```

but I am very hesitant to actually change the variable names

**Comment by kieranjmartin** [comment]
The problem with labelling in the print method means we have to actually save the dataset names somewhere, which we don't currently... 

i think in practice this may be more of a nice to have than practical. I imagine the way to do it would be to set  col limit to base and compare in the print method, so that any dataset name would be cut off if too long, and be expanded (with whitespace) if too short.

**Comment by gowerc** [comment]
on a related note would it be worth renaming the variables to `Base` and `Compare` (instead of `BASE` and `COMPARE` ) to be easier on the eyes ?

**Comment by kieranjmartin** [comment]
That would probably be nice, maybe raise a seperate issue and close this one, as I don't think its very practical unfortunately.

**Comment by gowerc** [comment]
Sure - I will leave it open for now though as a consideration.  I think the names is something that we can improve upon, I'm just not exactly sure how at the moment.

**Comment by gowerc** [comment]
Will close this issue now as I don't think we are going to do dynamic names for the datasets( please re-open if you disagree)
